// Issues Get All
export const GET_ISSUES = 'GET_ISSUES';
export const GET_ISSUES_LOADING = 'GET_ISSUES_LOADING';
export const GET_ISSUES_ERROR = 'GET_ISSUES_ERROR';

// Issue Get one
export const GET_AN_ISSUE = 'GET_AN_ISSUE';
export const GET_AN_ISSUE_LOADING = 'GET_AN_ISSUE_LOADING';
export const GET_AN_ISSUE_ERROR = 'GET_AN_ISSUE_ERROR';

// Issues Search
export const SEARCH_AN_ISSUE = 'SEARCH_AN_ISSUE';
export const SEARCH_AN_ISSUE_LOADING = 'SEARCH_AN_ISSUE_LOADING';
export const SEARCH_AN_ISSUE_ERROR = 'SEARCH_AN_ISSUE_ERROR';

// Filter Issue
export const FILTER_AN_ISSUE = 'FILTER_AN_ISSUE';
export const FILTER_AN_ISSUE_LOADING = 'FILTER_AN_ISSUE_LOADING';
export const FILTER_AN_ISSUE_ERROR = 'FILTER_AN_ISSUE_ERROR';

// Default Error Message
export const DEFAULT_ERROR_MESSAGE = 'DEFAULT_ERROR_MESSAGE';
